routes/web.php
<?php

use App\Http\Controllers\ProjectController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('/');
Route::get('/project/{slug}', [WelcomeController::class, 'showBySlug'])->name('project.byslug');
Route::get('/about', [WelcomeController::class, 'about'])->name('about');

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('projects', ProjectController::class);

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'category',
        'portfolio',
        'description',
    ];

    // Automatically generate a slug when creating or updating a project
    public static function boot()
    {
        parent::boot();

        static::creating(function ($project) {
            $project->slug = Str::slug($project->name);
        });

        static::updating(function ($project) {
            $project->slug = Str::slug($project->name);
        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProjectController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $projects = Project::all();

        return view('pages.projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.projects.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'category' => 'required|string',
            'portfolio' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'description' => 'required|string',
            'url' => 'nullable',
        ]);

        // Handle image upload
        $imagePath = $request->file('portfolio')->store('public/project_images');

        Project::create([
            'name' => $request->input('name'),
            'category' => $request->input('category'),
            'portfolio' => $imagePath,
            'description' => $request->input('description'),
            'url' => $request->input('url'),
        ]);

        return redirect()->route('projects.index')
            ->with('success', 'Project created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $item = Project::findOrFail($id);

        return view('pages.projects.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $project = Project::findOrFail($id);

        return view('pages.projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string',
            'category' => 'required|string',
            'description' => 'required|string',
            'url' => 'nullable',
        ]);

        $project = Project::findOrFail($id);

        // Update project details
        $project->update([
            'name' => $request->input('name'),
            'category' => $request->input('category'),
            'description' => $request->input('description'),
            'url' => $request->input('url'),
        ]);

        // If a new image is uploaded, update the image
        if ($request->hasFile('portfolio')) {
            $request->validate([
                'portfolio' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            // Handle image upload
            $imagePath = $request->file('portfolio')->store('public/project_images');

            // Update the project's portfolio image path
            $project->update(['portfolio' => $imagePath]);
        }

        return redirect()->route('projects.index')->with('success', 'Project updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // Delete the image file when deleting the project

        $project = Project::findOrFail($id);

        if ($project->portfolio) {
            Storage::delete($project->portfolio);
        }

        $project->delete();

        return redirect()->route('projects.index')
            ->with('success', 'Project deleted successfully');
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        $projects = Project::all();

        return view('welcome.index', compact('projects'));
    }

    public function showBySlug($slug)
    {
        $project = Project::where('slug', $slug)->firstOrFail();

        return view('welcome.show', compact('project'));
    }

    public function about()
    {
        return view('welcome.about');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/css.blade.php
<!-- Favicons -->
<link href="{{ url('assets/img/favicon.png') }}" rel="icon">
<link href="{{ url('assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

<!-- Google Fonts -->
<link
    href="https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="{{ url('assets/vendor/aos/aos.css') }}" rel="stylesheet">
<link href="{{ url('assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url('assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
<link href="{{ url('assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="{{ url('assets/css/style.css') }}" rel="stylesheet">

resources/views/includes/footer.blade.php
<footer class="footer" role="contentinfo">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <p class="mb-1">&copy; Copyright AqrisT.Satria. All Rights Reserved</p>
                <div class="credits">
                    Designed by <a href="https://aqristsatria.my.id/">AqrisT.Satria</a>
                </div>
            </div>
        </div>
    </div>
</footer>

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

resources/views/includes/js.blade.php
<!-- Vendor JS Files -->
<script src="{{ url('assets/vendor/aos/aos.js') }}"></script>
<script src="{{ url('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url('assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
<script src="{{ url('assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ url('assets/vendor/php-email-form/validate.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ url('assets/js/main.js') }}"></script>

resources/views/includes/navbar.blade.php
 <!-- ======= Navbar ======= -->
 <div class="collapse navbar-collapse custom-navmenu" id="main-navbar">
     <div class="container py-2 py-md-5">
         <div class="row align-items-start">
             <div class="col-md-2">
                 <ul class="custom-menu">
                     <li class="active"><a href="{{ route('/') }}">Home</a></li>
                     <li><a href="{{ route('about') }}">About Me</a></li>
                 </ul>
             </div>
             <div class="col-md-6 d-none d-md-block  mr-auto">
                 <div class="tweet d-flex">

                 </div>
             </div>
             <div class="col-md-4 d-none d-md-block">
                 <h3>Hire Me</h3>
                 <p>Thank you for visiting my profile, and I look forward to the opportunity to bring your digital ideas
                     to life!<br> <a href="#">aqrist@gmail.com</a>
                 </p>
             </div>
         </div>

     </div>
 </div>

 <nav class="navbar navbar-light custom-navbar">
     <div class="container">
         <a class="navbar-brand" href="{{ route('/') }}">AqrisT.Satria.</a>
         <a href="#" class="burger" data-bs-toggle="collapse" data-bs-target="#main-navbar">
             <span></span>
         </a>
     </div>
 </nav>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('projects.index') }}">Projects</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    @stack('addon-script')
</body>

</html>

resources/views/layouts/portfolio.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>
        Aqris T. Satria
        @yield('title')
    </title>

    <meta
        content="Hello, I'm Aqris T. Satria, a dedicated web and mobile developer with a passion for
    creating innovative digital solutions. With a background deeply rooted in technology, I thrive on
    transforming ideas into functional and aesthetically pleasing applications that leave a lasting
    impact."
        name="description">
        
    <meta content="web, html, css, js, laravel, mobile, app, development" name="keywords">

    @include('includes.css')
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-25YYY0BM44"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-25YYY0BM44');
    </script>
</head>

<body>

    <!-- ======= Navbar ======= -->
    @include('includes.navbar')

    <main id="main">

        @yield('content')


    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    @include('includes.footer')

    @include('includes.js')

</body>

</html>

resources/views/pages/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-5">
        <h2>Create Project</h2>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('projects.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <input type="text" class="form-control" id="category" name="category" required>
            </div>
            <div class="mb-3">
                <label for="portfolio" class="form-label">Portfolio Image</label>
                <input type="file" class="form-control" id="portfolio" name="portfolio" required>
            </div>
            <div class="mb-3">
                <label for="url" class="form-label">Url *if any</label>
                <input type="text" class="form-control" id="url" name="url">
            </div>

            {{-- CKEditor container --}}
            <div class="mb-3">
                <label for="description" class="form-label">Description (CKEditor)</label>
                <textarea class="form-control" id="description" name="description" rows="10"></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


@endsection

@push('addon-script')
    {{-- CKEditor CDN --}}
    <script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor.create(document.querySelector('#description'))
            .catch(error => {
                console.error(error);
            });
    </script>
@endpush

resources/views/pages/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-5">
        <h2>Edit Project</h2>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('projects.update', $project->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT') {{-- Use PUT method for updates --}}

            {{-- Existing project details --}}
            <input type="hidden" name="id" value="{{ $project->id }}">

            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ $project->name }}"
                    required>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <input type="text" class="form-control" id="category" name="category" value="{{ $project->category }}"
                    required>
            </div>
            <div class="mb-3">
                <label for="portfolio" class="form-label">Portfolio Image</label>
                <input type="file" class="form-control" id="portfolio" name="portfolio">
            </div>
            <div class="mb-3">
                <label for="url" class="form-label">Url *if any</label>
                <input type="text" class="form-control" id="url" name="url" value="{{ $project->url }}">
            </div>

            {{-- CKEditor container --}}
            <div class="mb-3">
                <label for="description" class="form-label">Description (CKEditor)</label>
                <textarea class="form-control" id="description" name="description" rows="10">{{ $project->description }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

@push('addon-script')
    {{-- CKEditor CDN --}}
    <script src="https://cdn.ckeditor.com/ckeditor5/23.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor.create(document.querySelector('#description'))
            .catch(error => {
                console.error(error);
            });
    </script>
@endpush

resources/views/pages/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-5">
        <h2>Projects</h2>
        <a href="{{ route('projects.create') }}" class="btn btn-primary mb-3">Create Project</a>

        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($projects as $project)
                    <tr>
                        <td>{{ $project->id }}</td>
                        <td>{{ $project->name }}</td>
                        <td>{{ $project->category }}</td>
                        <td>
                            <a href="{{ route('projects.show', $project->id) }}" class="btn btn-info">View</a>
                            <a href="{{ route('projects.edit', $project->id) }}" class="btn btn-warning">Edit</a>
                            <form action="{{ route('projects.destroy', $project->id) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Are you sure?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/pages/projects/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-5">
        <h2>Project Details</h2>
        <a href="{{ route('projects.index') }}" class="btn btn-secondary mb-3">Back to List</a>

        <dl class="row">
            <dt class="col-sm-3">ID</dt>
            <dd class="col-sm-9">{{ $item->id }}</dd>

            <dt class="col-sm-3">Name</dt>
            <dd class="col-sm-9">{{ $item->name }}</dd>

            <dt class="col-sm-3">Category</dt>
            <dd class="col-sm-9">{{ $item->category }}</dd>

            <dt class="col-sm-3">Description</dt>
            <dd class="col-sm-9">{!! $item->description !!}</dd>

            <dt class="col-sm-3">Portfolio Image</dt>
            <dd class="col-sm-9">
                @if ($item->portfolio)
                    <img src="{{ Storage::url($item->portfolio) }}" alt="Portfolio Image" class="img-fluid">
                @else
                    No image available.
                @endif
            </dd>
        </dl>
    </div>
@endsection

resources/views/welcome/about.blade.php
@extends('layouts.portfolio')

@section('title')
    About
@endsection
@section('content')
    <section class="section pb-5">
        <div class="container">
            <div class="row mb-5 align-items-end">
                <div class="col-md-6" data-aos="fade-up">

                    <h2>About Me</h2>
                    <p class="mb-0">Hello, I'm Aqris T. Satria, a dedicated web and mobile developer with a passion for
                        creating innovative digital solutions. With a background deeply rooted in technology, I thrive on
                        transforming ideas into functional and aesthetically pleasing applications that leave a lasting
                        impact.</p>
                </div>

            </div>

            <div class="row">
                <div class="col-md-4 ml-auto order-2" data-aos="fade-up">
                    <h3 class="h3 mb-4">Skills</h3>
                    <ul class="list-unstyled">
                        <li class="mb-3">
                            <div class="d-flex mb-1">
                                <strong>PHP/Laravel</strong>
                                <span class="ml-auto">96%</span>
                            </div>
                            <div class="progress custom-progress">
                                <div class="progress-bar" role="progressbar" style="width: 96%" aria-valuenow="96"
                                    aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </li>
                        <li class="mb-3">
                            <div class="d-flex mb-1">
                                <strong>UI/UX</strong>
                                <span class="ml-auto">78%</span>
                            </div>
                            <div class="progress custom-progress">
                                <div class="progress-bar" role="progressbar" style="width: 78%" aria-valuenow="78"
                                    aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </li>
                        <li class="mb-3">
                            <div class="d-flex mb-1">
                                <strong>HTML5/CSS3</strong>
                                <span class="ml-auto">99%</span>
                            </div>
                            <div class="progress custom-progress">
                                <div class="progress-bar" role="progressbar" style="width: 99%" aria-valuenow="99"
                                    aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </li>
                        <li class="mb-3">
                            <div class="d-flex mb-1">
                                <strong>Dart/Flutter</strong>
                                <span class="ml-auto">87%</span>
                            </div>
                            <div class="progress custom-progress">
                                <div class="progress-bar" role="progressbar" style="width: 87%" aria-valuenow="87"
                                    aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </li>
                    </ul>
                </div>

                <div class="col-md-7 mb-5 mb-md-0" data-aos="fade-up">
                    {{-- <p><img src="assets/img/person_1_sq.jpg" alt="Image" class="img-fluid"></p> --}}
                    <p>
                        I hold a strong foundation in web and mobile development, specializing in a variety of technologies
                        to bring projects to life. My journey in the tech world has equipped me with the skills needed to
                        craft responsive and efficient web interfaces, as well as seamless mobile applications.
                    </p>
                </div>

            </div>

        </div>

    </section>
@endsection

resources/views/welcome/show.blade.php
@extends('layouts.portfolio')


@section('title')
    {{ $project->name }}
@endsection

@section('content')
    <section class="section">

        <div class="site-section pb-0">
            <div class="container">
                <div class="row align-items-stretch">
                    <div class="col-md-8" data-aos="fade-up">
                        <img src="{{ Storage::url($project->portfolio) }}" alt="Image" class="img-fluid">
                    </div>
                    <div class="col-md-3 ml-auto" data-aos="fade-up" data-aos-delay="100">
                        <div class="sticky-content">
                            <h3 class="h3">{{ $project->name }}</h3>
                            <p class="mb-4"><span class="text-muted">{{ $project->web }}</span></p>

                            <div class="mb-5">
                                <p>
                                    {!! $project->description !!}
                                </p>

                            </div>

                            {{-- <h4 class="h4 mb-3">What I did</h4>
                            <ul class="list-unstyled list-line mb-5">
                                <li>Design</li>
                                <li>HTML5/CSS3</li>
                                <li>CMS</li>
                                <li>Logo</li>
                            </ul> --}}

                            @if ($project->url != null)
                                <p><a href="{{ $project->url }}" class="readmore">Visit Website</a></p>
                            @else
                            @endif

                        </div>
                    </div>
                </div>
            </div>
    </section>
@endsection